# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # Required to make flake8 read from pyproject.toml for now :(
        additional_dependencies: ["flake8-pyproject"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        language_version: "3.10"
        additional_dependencies:
          [
            "types-requests",
            "sqlalchemy-stubs",
            "types-pyYAML",
            "types-pkg-resources",
          ]
