---
- name: Start a Postgres container
  command: >-
    docker run -d --name check-db-schema-postgres
    -e POSTGRES_PASSWORD=check-db-schema
    -p 5432
    postgres:15-bookworm
- name: Wait for Postgres to accept connections
  command: docker exec check-db-schema-postgres pg_isready -U postgres
  register: pg_isready
  until: pg_isready.rc == 0
  retries: 30
  delay: 1
- name: Get the container port
  command: docker port check-db-schema-postgres 5432/tcp
  register: container_port
- name: Export the server URI
  set_fact:
    tox_environment:
      CHECK_DB_SCHEMA_SERVER_URI: "postgresql://postgres:check-db-schema@{{ container_port.stdout | trim }}"
