enabled_plugins:
    backends:
        - xivo
    services:
        - lookup
    views:
        - default_json

views:
    displays:
        default_display:
            -
                title: Firstname
                field: firstname
            -
                title: Lastname
                field: lastname
            -
                title: Number
                default:
                field: number
            -
                title: Mobile
                default:
                mobile_phone_number:
    profile_to_display:
        default: default_display

services:
    lookup:
        default:
            sources:
                - xivo_america
