version: '3'
services:
  sync:
    image: wazopbx/wait
    depends_on:
      - auth
      - dird
      - db
      - rabbitmq
    environment:
      TARGETS: "dird:9489 auth:9497 db:5432 rabbitmq:5672"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.all_routes.disable_service_discovery.yml:/etc/wazo-dird/conf.d/disable_service_discovery.yml"
      - "./etc/wazo-dird/conf.d/asset.all_routes.db_uri.yml:/etc/wazo-dird/conf.d/db_uri.yml"
      - "./etc/wazo-dird/conf.d/asset.all_routes.auth.yml:/etc/wazo-dird/conf.d/auth.yml"
      - "./etc/wazo-dird/conf.d/asset.all_routes.other.yml:/etc/wazo-dird/conf.d/other.yml"
      - "./etc/wazo-dird/conf.d/asset.all_routes.yml:/etc/wazo-dird/config.yml"
      - "./tmp/data/asset.all_routes.test.csv:/tmp/data/test.csv"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
