services:
  sync:
    depends_on:
      - auth
      - dird
      - microsoft.com
      - db
      - rabbitmq
    environment:
      TARGETS: "auth:9497 dird:9489 microsoft.com:443 db:5432 rabbitmq:5672"
