services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: "wazoplatform/wazo-auth-mock"
    ports:
      - "9497"

  dird:
    image: wazo-dird-test
    ports:
      - "9489"
    volumes:
      - "../..:/usr/src/wazo-dird"
      - "./etc/wazo-dird/conf.d/50-default.yml:/etc/wazo-dird/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/wazo-auth-client/wazo_auth_client:/opt/venv/lib/python3.9/site-packages/wazo_auth_client"
      # - "${LOCAL_GIT_REPOS}/wazo-bus/wazo_bus:/opt/venv/lib/python3.9/site-packages/wazo_bus"

  db:
    image: wazoplatform/wazo-dird-db:local
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  people.googleapis.com:
    image: jamesdbloom/mockserver:mockserver-5.7.0
    user: root
    ports:
      - "443"
    command: ["-serverPort", "443"]

  microsoft.com:
    image: jamesdbloom/mockserver:mockserver-5.7.0
    user: root
    ports:
      - "443"
    command: ["-serverPort", "443"]
