version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - people.googleapis.com
      - db
      - rabbitmq
    environment:
      TARGETS: "auth:9497 dird:9489 people.googleapis.com:443 db:5432 rabbitmq:5672"
